# Generated by Django 4.2.19 on 2025-03-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="user_id",
        ),
        migrations.AddField(
            model_name="feed",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
