# Generated by Django 4.2.19 on 2025-03-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_bookmark_like_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="like_count",
        ),
    ]
